In [389]:
import torch
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from helper_function import plot_decision_boundary, plot_loss_curves, plot_predictions


In [390]:
device = torch.accelerator.current_accelerator().type

In [391]:
device

'cuda'

In [392]:
torch.set_default_device(device)

In [393]:
# Set the hyperparameters for data creation
NUM_CLASSES = 5
NUM_FEATURES = 5
RANDOM_SEED = 42

In [394]:
X_blob, y_blob = make_blobs(n_samples=1000,n_features=NUM_FEATURES,centers=NUM_CLASSES,random_state=RANDOM_SEED,cluster_std=1.5)

In [395]:
X_blob[:5]

array([[-7.15631668, -6.38354406,  2.75344642,  0.38577558, -4.30630122],
       [-0.6744412 ,  7.98913844,  3.87509247, -1.75374768, -5.49988593],
       [ 0.90444432,  9.62362616,  3.99196553,  4.76312019, -5.07900987],
       [-1.72326862,  8.13215589,  4.43977755,  3.57966438, -7.75382809],
       [ 3.67621869, -5.28204487, -5.09547799, -3.27041737,  0.98636802]])

In [396]:
X_blob_data = torch.from_numpy(X_blob).type(dtype=torch.float).to(device)
y_blob_data = torch.from_numpy(y_blob).type(dtype=torch.float).to(device)

In [397]:
X_blob_data.dtype,X_blob_data.shape

(torch.float32, torch.Size([1000, 5]))

In [398]:
X_train, X_test, y_train , y_test = train_test_split(X_blob_data,y_blob,test_size=0.2,random_state=42)

In [399]:
y_train = torch.from_numpy(y_train).type(torch.long).to(device)
y_test = torch.from_numpy(y_test).type(torch.long).to(device)

In [400]:
torch.cuda.manual_seed(42)
torch.manual_seed(42)

In [401]:
X_train[:2]

tensor([[ -8.1923, -12.2529,   7.7509,   2.3329,   5.8749],
        [  5.4546,  -5.8681,  -2.7028,  -1.9657,  -1.4296]], device='cuda:0')

In [402]:
import torch.nn as nn
from torch.nn import Sequential
from torch.nn import CrossEntropyLoss
from torch.optim import Adam


In [ ]:
class MulticlassClassification(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(5,20)
        self.layer2 = nn.Linear(20,30)
        self.layer3 = nn.Linear(30,20)
        self.layer4 = nn.Linear(20,5)
        self.relu = nn.ReLU()
        

    def forward(self,X:torch.Tensor)-> torch.Tensor:
        x = self.relu(self.layer1(X))
        x = self.relu(self.layer2(x))
        x = self.relu(self.layer3(x))
        x = self.relu(self.layer4(x))
        """
            x = nn.Softmax(x) # Begginer Mistake dont use this cus the BCELoss will do this for you
        """
        return x

In [404]:
model = MulticlassClassification()


In [405]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1010, -0.4382, -0.0909, -0.4112, -0.3074],
         [-0.0157,  0.2113, -0.0841,  0.0169, -0.1908],
         [-0.2311,  0.3782,  0.2951, -0.4166, -0.1003],
         [-0.3735,  0.2452, -0.1975,  0.0124, -0.2622],
         [-0.4406,  0.3354,  0.4188, -0.3398, -0.2708],
         [-0.0445, -0.4015, -0.0097,  0.3874, -0.1067],
         [-0.4017, -0.2091,  0.1337, -0.2080, -0.2922],
         [ 0.3188, -0.2002, -0.2600, -0.3836,  0.2416],
         [ 0.0984, -0.1392,  0.4340, -0.0276,  0.3760],
         [ 0.1903, -0.3532,  0.2807, -0.3495,  0.0983],
         [-0.2906,  0.3047,  0.3314,  0.2045, -0.2200],
         [-0.2981,  0.2030, -0.0906, -0.2061,  0.2710],
         [-0.0797, -0.3153, -0.4268, -0.2387, -0.2416],
         [-0.0909, -0.0171, -0.1680,  0.1091, -0.1287],
         [ 0.1352,  0.3850, -0.2060, -0.4060,  0.4405],
         [-0.1978,  0.0096,  0.0845,  0.1042, -0.1528],
         [ 0.2716, -0.0035,  0.1769,  0.1294,  0.3630],
         [-0.1528, -0.281

In [406]:
model.state_dict()

OrderedDict([('layer1.weight',
              tensor([[ 0.1010, -0.4382, -0.0909, -0.4112, -0.3074],
                      [-0.0157,  0.2113, -0.0841,  0.0169, -0.1908],
                      [-0.2311,  0.3782,  0.2951, -0.4166, -0.1003],
                      [-0.3735,  0.2452, -0.1975,  0.0124, -0.2622],
                      [-0.4406,  0.3354,  0.4188, -0.3398, -0.2708],
                      [-0.0445, -0.4015, -0.0097,  0.3874, -0.1067],
                      [-0.4017, -0.2091,  0.1337, -0.2080, -0.2922],
                      [ 0.3188, -0.2002, -0.2600, -0.3836,  0.2416],
                      [ 0.0984, -0.1392,  0.4340, -0.0276,  0.3760],
                      [ 0.1903, -0.3532,  0.2807, -0.3495,  0.0983],
                      [-0.2906,  0.3047,  0.3314,  0.2045, -0.2200],
                      [-0.2981,  0.2030, -0.0906, -0.2061,  0.2710],
                      [-0.0797, -0.3153, -0.4268, -0.2387, -0.2416],
                      [-0.0909, -0.0171, -0.1680,  0.1091, -0.1287],
   

In [407]:
optim_fn = Adam(model.parameters(),lr=0.01)

In [408]:
loss_fn = CrossEntropyLoss()

In [409]:
model.to(device)
for epoch in range(0,10000):
    model.train()
    y_pred = model(X_train)
    loss = loss_fn(y_pred,y_train)
    optim_fn.zero_grad()
    loss.backward()
    optim_fn.step()
    if epoch % 10 == 0:
        print(f"Epoch: {epoch}| Loss: {loss.item()}")

AttributeError: 'MulticlassClassification' object has no attribute 'layer5'