In [67]:
import torch

In [68]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [69]:
scalar.ndim

0

In [70]:
scalar.size()

torch.Size([])

In [71]:
scalar.shape

torch.Size([])

In [72]:
tensor = torch.tensor(
    [
        [
            [1,2,3],
            [3,6,9],
            [2,4,5]
        ]
    ]
    )

tensor.shape, tensor.size(),tensor.ndim

(torch.Size([1, 3, 3]), torch.Size([1, 3, 3]), 3)

In [73]:
torch.zeros([3,3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [74]:

torch.ones([3,3,3]),print("\n"),torch.ones([2,3,3]),print("\n"),torch.ones([1,3,3]),print("\n"),torch.ones([3,3]),print("\n")

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 None)

In [75]:
torch.rand((2,3),dtype=torch.float16,requires_grad=True)

tensor([[0.9263, 0.1348, 0.8408],
        [0.1646, 0.7153, 0.3491]], dtype=torch.float16, requires_grad=True)

In [76]:
help(torch.rand)

Help on built-in function rand in module torch:

rand(...)
    rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`

    The shape of the tensor is defined by the variable argument :attr:`size`.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layou

In [77]:
torch.rand(1,2,3)

tensor([[[0.7594, 0.3541, 0.8738],
         [0.1284, 0.7251, 0.0341]]])

In [78]:
torch.rand((1,2,3))

tensor([[[0.5603, 0.8708, 0.1663],
         [0.4190, 0.0781, 0.2882]]])

In [79]:
t1 = torch.ones((2,2))
torch.rand_like(t1)

tensor([[0.9308, 0.1806],
        [0.2543, 0.8203]])

In [80]:
torch.rand_like(t1)

tensor([[0.0853, 0.0255],
        [0.3412, 0.1850]])

In [81]:
z = torch.zeros(size=[2,2])

z[0].dot(t1[0])

tensor(0.)

In [82]:
tr1 = torch.arange(0,10,2)
tr1

tensor([0, 2, 4, 6, 8])

In [83]:
tr1.reshape(5,1)

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

# Errors
1. Tensors not the right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [84]:
f16_tensor  = tr1.type(torch.float16)
f16_tensor

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)

In [85]:
torch.cuda.is_available()

True

In [86]:
tr1.max()

tensor(8)

In [87]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
x_reshaped =  x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [89]:
y = x.view(1,9)
y[:,0] = 10
y[:,0] = 10 # y[0:0] its the same , select the whole 0th dimenion and index into the 1st dimension

x, x.ndim

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), 1)

In [90]:
# Stack tensors on top of each others
x_stacked = torch.stack([x,x,x,x],dim=0) # default dim = 0 
x_stacked , x.shape


(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([9]))

In [91]:
x_stacked = torch.stack([x,x,x,x],dim=1) # default dim = 0 
x_stacked , x.shape

(tensor([[10., 10., 10., 10.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]),
 torch.Size([9]))

# Python Generators

Wtf are these ?

What is the difference between yield and generator ?

The function call when yield is presnt will happen only when there is a loop


In [92]:
def gen_demo():
    yield "first statement"
    yield "seccond statement"
    yield "third statement"

# gen = gen_demo()
gen = gen_demo


# print(next(gen))
# print(next(gen))
# print(next(gen))
# print(next(gen)) # this will thow an error cus we only have 3 yield statements we will get a StopIteraion error


# for i in gen:
for i in gen():
    print(i)


first statement
seccond statement
third statement


In [93]:
def gen_demo():
    yield "first statement"
    yield "seccond statement"
    return "third statement"

# 1. Create the generator object
g = gen_demo()

# 2. Get first value
print(next(g))  # Output: "first statement"

# 3. Get second value
print(next(g))  # Output: "seccond statement"

# 4. Reach the return statement
try:
    print(next(g))
except StopIteration as e:
    print(f"Generator ended. Return value: {e.value}")
    # Output: "Generator ended. Return value: third statement"


first statement
seccond statement
Generator ended. Return value: third statement


In [94]:
def m_range(start,end):
    for i in range(start,end):
        yield i

In [95]:
gen = (i**2 for i in range(1,101))

# Python Multithreading

What is a thread ?

what is multi threading ?

what is multi processing ?


In [96]:
# classes and fucntions can be used to make threads

In [ ]:
from threading import Thread

class Hello:
    def do(self):
        for i in range(5):
            print("Hello",i+1)

class Hi:
    def do(self):
        for i in range(5):
            print("Hi",i+1)

In [98]:
t1 = Hello()
t2 = Hi()

In [99]:
t1.do()

Hello 1
Hello 2
Hello 3
Hello 4
Hello 5


In [100]:
t2.do()

Hi 1
Hi 2
Hi 3
Hi 4
Hi 5


In [102]:
# i want to run hello and hi together

t1 = Thread(target=Hello.do)
t2 = Thread(target=Hi.do)


In [106]:
class Hello(Thread):
    def run(self):
        for i in range(5):
            print("Hello",i+1)

class Hi(Thread):
    def run(self):
        for i in range(5):
            print("Hi",i+1)

In [147]:
t1 = Hello()
t2 = Hi()

In [148]:
t1.start()
t2.start()

print("bye")

Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hi 1
Hi 2
Hi 3
Hi 4
Hi 5
bye


# Squeeze and Unsqueeze


In [152]:
x_reshaped,x_reshaped.shape

(tensor([[10.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [153]:
x_reshaped.squeeze(dim=1),x_reshaped.squeeze(dim=1).shape

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]), torch.Size([9]))

In [154]:
x_suqeezed = x_reshaped.squeeze(dim=1)

In [162]:
x_suqeezed,x_suqeezed.shape,x_suqeezed.unsqueeze(dim=0),x_suqeezed.unsqueeze(dim=0).shape,x_suqeezed.unsqueeze(dim=1),x_suqeezed.unsqueeze(dim=1).shape


(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([9]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([1, 9]),
 tensor([[10.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [ ]:
# torch.permute permute is a view

tensor([[10.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]])

In [166]:
x = torch.randn(2,3,5)
x,x.shape

(tensor([[[-0.5146, -0.4549, -1.5460, -0.3398, -0.3516],
          [ 0.2127, -2.0879,  1.5146, -0.3721, -0.3514],
          [-0.2601,  0.6750,  1.7984,  0.6424, -1.1259]],
 
         [[-0.9242,  0.3159,  0.7282, -0.6064,  1.4546],
          [-0.9294,  0.3789, -0.7173, -0.2950, -0.7231],
          [-0.6472,  0.2023,  0.0670,  1.5368,  1.2875]]]),
 torch.Size([2, 3, 5]))

In [173]:
x_permuted = x.permute(2,1,0)
x_permuted

tensor([[[-0.5146, -0.9242],
         [ 0.2127, -0.9294],
         [-0.2601, -0.6472]],

        [[-0.4549,  0.3159],
         [-2.0879,  0.3789],
         [ 0.6750,  0.2023]],

        [[-1.5460,  0.7282],
         [ 1.5146, -0.7173],
         [ 1.7984,  0.0670]],

        [[-0.3398, -0.6064],
         [-0.3721, -0.2950],
         [ 0.6424,  1.5368]],

        [[-0.3516,  1.4546],
         [-0.3514, -0.7231],
         [-1.1259,  1.2875]]])

In [174]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [175]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [176]:
x[:,0]

tensor([[1, 2, 3]])

In [177]:
x[:,:,0]

tensor([[1, 4, 7]])

In [184]:
y = x[:,0,0].numpy()

y

array([1])

In [187]:
z = torch.from_numpy(y)
z

tensor([1])

tensor([1])