In [1]:
import torch

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [5]:
scalar.size()

torch.Size([])

In [7]:
scalar.shape

torch.Size([])

In [ ]:
tensor = torch.tensor(
    [
        [
            [1,2,3],
            [3,6,9],
            [2,4,5]
        ]
    ]
    )

tensor.shape, tensor.size(),tensor.ndim

(torch.Size([1, 3, 3]), torch.Size([1, 3, 3]), 3)

In [10]:
torch.zeros([3,3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:

torch.ones([3,3,3]),print("\n"),torch.ones([2,3,3]),print("\n"),torch.ones([1,3,3]),print("\n"),torch.ones([3,3]),print("\n")

(tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]),
 None,
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 None)

In [18]:
torch.rand((2,3),dtype=torch.float16,requires_grad=True)

tensor([[0.6812, 0.5601, 0.4824],
        [0.4683, 0.0132, 0.4927]], dtype=torch.float16, requires_grad=True)

In [20]:
help(torch.rand)

Help on built-in function rand in module torch:

rand(...)
    rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`

    The shape of the tensor is defined by the variable argument :attr:`size`.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layou

In [21]:
torch.rand(1,2,3)

tensor([[[0.2828, 0.6873, 0.3499],
         [0.2280, 0.7664, 0.9158]]])

In [22]:
torch.rand((1,2,3))

tensor([[[0.1178, 0.0366, 0.0584],
         [0.1240, 0.9655, 0.8312]]])

In [25]:
t1 = torch.ones((2,2))
torch.rand_like(t1)

tensor([[0.3085, 0.8872],
        [0.6721, 0.6584]])

In [31]:
torch.rand_like(t1)

tensor([[0.9883, 0.6951],
        [0.7577, 0.5186]])

In [37]:
z = torch.zeros(size=[2,2])

z[0].dot(t1[0])

tensor(0.)

In [40]:
tr1 = torch.arange(0,10,2)
tr1

tensor([0, 2, 4, 6, 8])

In [45]:
tr1.reshape(5,1)

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

# Errors
1. Tensors not the right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [59]:
f16_tensor  = tr1.type(torch.float16)
f16_tensor

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)

In [61]:
torch.cuda.is_available()

True

In [65]:
tr1.max()

tensor(8)