In [9]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [10]:
print(torch.__version__)

2.11.0+cu130


In [11]:
torch.cuda.is_available()

True

In [12]:
torch.manual_seed(42)

In [13]:
# Type casting
float_32_tensor = torch.arange(1,10,dtype=torch.float32,device="cpu",requires_grad=False)
float_32_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [15]:
torch.tensor([2,5,6],device="cpu",dtype=torch.float16,requires_grad=False)

tensor([2., 5., 6.], dtype=torch.float16)

In [18]:
# View, stack # squeeze and unsqueeze

t3 = torch.arange(0,5,dtype=torch.float32)
t3


tensor([0., 1., 2., 3., 4.])

In [19]:
t3.shape

torch.Size([5])

In [52]:
t3 = t3.reshape([1,5])
t3

tensor([[1., 1., 1., 1., 1.]])

In [53]:
v3 = t3.view(5,1)
v3,t3

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
 tensor([[1., 1., 1., 1., 1.]]))

In [54]:
v3[:,0]

tensor([1., 1., 1., 1., 1.])

In [55]:
t3@t3.T

tensor([[5.]])

In [59]:
t4 = torch.arange(1,6,device="cpu",dtype=torch.float32).reshape(1,5)
t4,t3


(tensor([[1., 2., 3., 4., 5.]]), tensor([[1., 1., 1., 1., 1.]]))

In [60]:
t4[0].dot(t3[0])

tensor(15.)