In [ ]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)

2.11.0+cu130


In [4]:
torch.cuda.is_available()

True

In [5]:
torch.manual_seed(42)

In [6]:
# Type casting
float_32_tensor = torch.arange(1,10,dtype=torch.float32,device="cpu",requires_grad=False)
float_32_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [8]:
torch.tensor([2,5,6],device="cpu",dtype=torch.float16,requires_grad=False)

tensor([2., 5., 6.], dtype=torch.float16)

In [9]:
# View, stack # squeeze and unsqueeze

t3 = torch.arange(0,5,dtype=torch.float32)
t3


tensor([0., 1., 2., 3., 4.])

In [10]:
t3.shape

torch.Size([5])

In [11]:
t3 = t3.reshape([1,5])
t3

tensor([[0., 1., 2., 3., 4.]])

In [12]:
v3 = t3.view(5,1)
v3,t3

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.]]),
 tensor([[0., 1., 2., 3., 4.]]))

In [13]:
v3[:,0]

tensor([0., 1., 2., 3., 4.])

In [14]:
t3@t3.T

tensor([[30.]])

In [15]:
t4 = torch.arange(1,6,device="cpu",dtype=torch.float32).reshape(1,5)
t4,t3


(tensor([[1., 2., 3., 4., 5.]]), tensor([[0., 1., 2., 3., 4.]]))

In [16]:
t4[0].dot(t3[0])

tensor(40.)

In [17]:
t_stacked = torch.stack([t3,t3,t3,t3])
t_stacked, t_stacked.shape

(tensor([[[0., 1., 2., 3., 4.]],
 
         [[0., 1., 2., 3., 4.]],
 
         [[0., 1., 2., 3., 4.]],
 
         [[0., 1., 2., 3., 4.]]]),
 torch.Size([4, 1, 5]))

In [18]:
t_stacked[:,0,:]

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])

In [19]:
t1 = torch.arange(1,6,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t2 = torch.arange(6,11,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t3 = torch.arange(11,16,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t4 = torch.arange(16,21,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)

t1,t2,t3,t4

(tensor([[1., 2., 3., 4., 5.]]),
 tensor([[ 6.,  7.,  8.,  9., 10.]]),
 tensor([[11., 12., 13., 14., 15.]]),
 tensor([[16., 17., 18., 19., 20.]]))

In [20]:
t_stacked = torch.stack([t1,t2,t3,t4])
t_stacked, t_stacked.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.,  9., 10.]],
 
         [[11., 12., 13., 14., 15.]],
 
         [[16., 17., 18., 19., 20.]]]),
 torch.Size([4, 1, 5]))

In [21]:
t_stacked[:,0,0:3],t_stacked[:,0,0:3].shape

(tensor([[ 1.,  2.,  3.],
         [ 6.,  7.,  8.],
         [11., 12., 13.],
         [16., 17., 18.]]),
 torch.Size([4, 3]))

In [22]:
t_stacked = torch.stack([t1,t2,t3,t4],dim=2)
t_stacked,t_stacked.shape

(tensor([[[ 1.,  6., 11., 16.],
          [ 2.,  7., 12., 17.],
          [ 3.,  8., 13., 18.],
          [ 4.,  9., 14., 19.],
          [ 5., 10., 15., 20.]]]),
 torch.Size([1, 5, 4]))

In [23]:
t1 = torch.arange(1,6,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t2 = torch.arange(6,11,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t3 = torch.arange(11,16,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t4 = torch.arange(16,21,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)

print(f"{t1}\n")
print(f"{t2}\n")
print(f"{t3}\n")
print(f"{t4}\n")

tensor([[1., 2., 3., 4., 5.]])

tensor([[ 6.,  7.,  8.,  9., 10.]])

tensor([[11., 12., 13., 14., 15.]])

tensor([[16., 17., 18., 19., 20.]])



In [24]:
torch.stack([t1,t2,t3,t4],dim=0)

tensor([[[ 1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10.]],

        [[11., 12., 13., 14., 15.]],

        [[16., 17., 18., 19., 20.]]])

In [25]:
torch.stack([t1,t2,t3,t4],dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]]])

In [26]:
torch.stack([t1,t2,t3,t4],dim=2)

tensor([[[ 1.,  6., 11., 16.],
         [ 2.,  7., 12., 17.],
         [ 3.,  8., 13., 18.],
         [ 4.,  9., 14., 19.],
         [ 5., 10., 15., 20.]]])

# Stacking Notes

`You index into the stack by entering the dimesion for instance when dim =2 you enter the secent dimension and then choose an element each from the dimesion and then stack it` 

In [30]:
# torch.cat()
# torch.split()
# torch.chunk()

torch.manual_seed(42)
x = torch.randn(2,3)
torch.manual_seed(43)
y = torch.randn(2,3)
torch.manual_seed(44)
z = torch.randn(2,3)

x,y,z

(tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]]),
 tensor([[-0.6484, -0.7058,  0.6432],
         [ 1.4788,  1.1918, -0.1446]]),
 tensor([[ 0.0589, -1.3945,  0.8448],
         [ 0.1268,  1.0822, -1.1731]]))

In [31]:
torch.cat([x,y,z],dim=1)

tensor([[ 0.3367,  0.1288,  0.2345, -0.6484, -0.7058,  0.6432,  0.0589, -1.3945,
          0.8448],
        [ 0.2303, -1.1229, -0.1863,  1.4788,  1.1918, -0.1446,  0.1268,  1.0822,
         -1.1731]])

In [33]:
help(torch.chunk)

Help on built-in function chunk in module torch:

chunk(...)
    chunk(input: Tensor, chunks: int, dim: int = 0) -> Tuple[Tensor, ...]

    Attempts to split a tensor into the specified number of chunks. Each chunk is a view of
    the input tensor.


    .. note::

        This function may return fewer than the specified number of chunks!

    .. seealso::

        :func:`torch.tensor_split` a function that always returns exactly the specified number of chunks

    If the tensor size along the given dimension :attr:`dim` is divisible by :attr:`chunks`,
    all returned chunks will be the same size.
    If the tensor size along the given dimension :attr:`dim` is not divisible by :attr:`chunks`,
    all returned chunks will be the same size, except the last one.
    If such division is not possible, this function may return fewer
    than the specified number of chunks.

    Arguments:
        input (Tensor): the tensor to split
        chunks (int): number of chunks to return
        

In [43]:
x

s = torch.stack([x,x,x],dim=0)
s, x.shape , s.shape

(tensor([[[ 0.3367,  0.1288,  0.2345],
          [ 0.2303, -1.1229, -0.1863]],
 
         [[ 0.3367,  0.1288,  0.2345],
          [ 0.2303, -1.1229, -0.1863]],
 
         [[ 0.3367,  0.1288,  0.2345],
          [ 0.2303, -1.1229, -0.1863]]]),
 torch.Size([2, 3]),
 torch.Size([3, 2, 3]))

In [52]:
# torch.chunk() # will result in a view of the original tensor while
torch.chunk(s, chunks = 3, dim = 2)

(tensor([[[0.3367],
          [0.2303]],
 
         [[0.3367],
          [0.2303]],
 
         [[0.3367],
          [0.2303]]]),
 tensor([[[ 0.1288],
          [-1.1229]],
 
         [[ 0.1288],
          [-1.1229]],
 
         [[ 0.1288],
          [-1.1229]]]),
 tensor([[[ 0.2345],
          [-0.1863]],
 
         [[ 0.2345],
          [-0.1863]],
 
         [[ 0.2345],
          [-0.1863]]]))

In [55]:
t1 = torch.arange(1,6,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t2 = torch.arange(6,11,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t3 = torch.arange(11,16,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)
t4 = torch.arange(16,21,device="cpu",dtype=torch.float32,requires_grad=False).reshape(1,5)

print(f"{t1}\n")
print(f"{t2}\n")
print(f"{t3}\n")
print(f"{t4}\n")

tensor([[1., 2., 3., 4., 5.]])

tensor([[ 6.,  7.,  8.,  9., 10.]])

tensor([[11., 12., 13., 14., 15.]])

tensor([[16., 17., 18., 19., 20.]])



In [56]:
help(torch.split)

Help on function split in module torch.functional:

split(tensor: torch.Tensor, split_size_or_sections: int | list[int], dim: int = 0) -> tuple[torch.Tensor, ...]
    Splits the tensor into chunks. Each chunk is a view of the original tensor.

    If :attr:`split_size_or_sections` is an integer type, then :attr:`tensor` will
    be split into equally sized chunks (if possible). Last chunk will be smaller if
    the tensor size along the given dimension :attr:`dim` is not divisible by
    :attr:`split_size`.

    If :attr:`split_size_or_sections` is a list, then :attr:`tensor` will be split
    into ``len(split_size_or_sections)`` chunks with sizes in :attr:`dim` according
    to :attr:`split_size_or_sections`.

    Args:
        tensor (Tensor): tensor to split.
        split_size_or_sections (int) or (list(int)): size of a single chunk or
            list of sizes for each chunk
        dim (int): dimension along which to split the tensor.

    Example::

        >>> a = torch.arange(

In [58]:
help(torch.functional)

Help on module torch.functional in torch:

NAME
    torch.functional - # mypy: allow-untyped-defs

FUNCTIONS
    align_tensors(*tensors)

    atleast_1d(*tensors)
        Returns a 1-dimensional view of each input tensor with zero dimensions.
        Input tensors with one or more dimensions are returned as-is.

        Args:
            input (Tensor or sequence of Tensors): tensor(s) to be converted to at least 1-dimensional.

        Returns:
            output (Tensor or tuple of Tensors)

        Example::

            >>> x = torch.arange(2)
            >>> x
            tensor([0, 1])
            >>> torch.atleast_1d(x)
            tensor([0, 1])
            >>> x = torch.tensor(1.)
            >>> x
            tensor(1.)
            >>> torch.atleast_1d(x)
            tensor([1.])
            >>> x = torch.tensor(0.5)
            >>> y = torch.tensor(1.)
            >>> torch.atleast_1d((x, y))
            (tensor([0.5000]), tensor([1.]))
            >>> torch.atleast_1d()
   