In [1]:
import torch

In [2]:
import torch.nn as nn

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 5070 Laptop GPU'

In [6]:
torch.cuda.get_device_capability()

(12, 0)

In [7]:
# Create randomdata
# train_test split the data
# train a linearRegression Model
# predit values

In [11]:
X = torch.arange(1,101,0.5).unsqueeze(dim=1)
X[:5],X.shape

(tensor([[1.0000],
         [1.5000],
         [2.0000],
         [2.5000],
         [3.0000]]),
 torch.Size([200, 1]))

In [56]:
torch.manual_seed(42)
weight = torch.randn(1,dtype=torch.float)
bias = torch.randn(1,dtype=torch.float)

y = weight*X + bias
weight,bias

(tensor([0.3367]), tensor([0.1288]))

In [57]:
train_size = int(len(X) * 0.8)
train_size

160

In [58]:
X_train,y_train = X[:train_size],y[:train_size]
X_test,y_test = X[train_size:],y[train_size:]

X_train.size(), X_test.size(), y[:5]

(torch.Size([160, 1]),
 torch.Size([40, 1]),
 tensor([[0.4655],
         [0.6338],
         [0.8022],
         [0.9705],
         [1.1389]]))

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        torch.manual_seed(50)
        self.weight = nn.Parameter(torch.randn(1,dtype=torch.float,requires_grad=True))
        self.bias = nn.Parameter(torch.randn(1,dtype=torch.float))

    def forward(self,x:torch.Tensor) -> torch.Tensor:
        return self.weight*x + self.bias
        

In [67]:
model0 = LinearRegression()

In [68]:
list(model0.parameters())

[Parameter containing:
 tensor([0.4625], requires_grad=True),
 Parameter containing:
 tensor([-0.1692], requires_grad=True)]

In [72]:
model0.state_dict()

OrderedDict([('weight', tensor([0.4625])), ('bias', tensor([-0.1692]))])

In [77]:
with torch.inference_mode():
    y_pred = model0(X_test)

loss = y_test[:5] - y_pred[:5]
y_pred[:5],y_test[:5],loss

(tensor([[37.2926],
         [37.5238],
         [37.7551],
         [37.9863],
         [38.2176]]),
 tensor([[27.4007],
         [27.5691],
         [27.7374],
         [27.9058],
         [28.0741]]),
 tensor([[ -9.8918],
         [ -9.9547],
         [-10.0177],
         [-10.0805],
         [-10.1434]]))

In [78]:
# inference mode turns of gradient tracking

In [79]:
# Model Training  => loss and optimizer
from torch.nn import L1Loss
from torch.optim import Adam

loss_fn = L1Loss()
opt_fn = Adam(params=model0.parameters(),lr=0.01)

In [ ]:
# Very important Flow
# Forward Pass
# Claculate Loss
# Zero Gradients
# Perfrom Backpropagation
# Update the optimizer

In [81]:
epochs = range(0,101)

for epoch in epochs:
    
    model0.train()
    y_pred = model0(X_train)
    loss = loss_fn(y_pred,y_train)
    opt_fn.zero_grad()
    loss.backward()
    opt_fn.step()

In [ ]:
model0.eval()

with torch.inference_mode():
    y_pred = model0(X_test)